openapi: 3.1.0

info:
  title: Multi-task Order API
  version: 1.3.0-SNAPSHOT

paths: {}

components:
  schemas:
    OrderDto:
      type: object
      required:
        - id
        - code
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string

    Meta:
      type: object
      properties:
        serverTime:
          type: string
          format: date-time
      x-ignore-model: true

    PageOrderDto:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/OrderDto"
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
      x-ignore-model: true

    ServiceResponsePageOrderDto:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/PageOrderDto"
        meta:
          $ref: "#/components/schemas/Meta"
      x-api-wrapper: true
      x-api-wrapper-type: io.github.blueprintplatform.openapi.generics.contract.envelope.ServiceResponse
      x-api-wrapper-datatype: PageOrderDto
      x-data-container: Page
      x-data-container-type: io.github.blueprintplatform.openapi.generics.contract.paging.Page
      x-data-item: OrderDto
