<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.blueprint-platform.samples</groupId>
        <artifactId>samples</artifactId>
        <version>1.2.1</version>
    </parent>

    <artifactId>domain-contracts</artifactId>
    <packaging>pom</packaging>

    <name>domain-contracts</name>
    <description>Domain-based shared contracts (modular structure for microservices)</description>

    <modules>
        <module>customer-contract</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>