server:
  port: ${APP_PORT:8084}
  servlet:
    context-path: /customer-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: customer-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    io.github.bsayli: DEBUG

app:
  openapi:
    version: @project.version@
    base-url: "http://localhost:${server.port}${server.servlet.context-path:}"
    wrapper:
      # Optional: extra annotation for generated client models
      # class-extra-annotation: "@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)"
      # Generic container types to auto-enrich (supports multiple)
      generic-containers:
        - Page
        # - Slice
        # - PagedResult

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json