server:
  port: ${APP_PORT:8084}
  servlet:
    context-path: /customer-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: customer-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.demo: DEBUG

app:
  openapi:
    version: @project.version@
    base-url: "http://localhost:${server.port}${server.servlet.context-path:}"

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json