package io.github.bsayli.openapi.generics.server.core.schema;

import io.github.bsayli.openapi.generics.server.core.schema.contract.PropertyNames;
import io.github.bsayli.openapi.generics.server.core.schema.contract.SchemaNames;
import io.github.bsayli.openapi.generics.server.core.schema.contract.VendorExtensions;
import io.swagger.v3.oas.models.media.ComposedSchema;
import io.swagger.v3.oas.models.media.ObjectSchema;
import io.swagger.v3.oas.models.media.Schema;

import java.util.List;

/**
 * Factory responsible for creating contract-aware OpenAPI wrapper schemas for
 * {@code ServiceResponse<T>} based response types.
 *
 * <p>This factory is the <b>authoritative source</b> of wrapper schema structure.
 *
 * <h2>Key Responsibilities</h2>
 *
 * <ul>
 *   <li>Create wrapper schemas using {@code allOf} composition</li>
 *   <li>Attach required vendor extensions for contract semantics</li>
 * </ul>
 *
 * <h2>Design Principles</h2>
 *
 * <ul>
 *   <li><b>Single source of truth</b> → wrapper structure is defined only here</li>
 *   <li><b>Deterministic</b> → same input produces identical schema</li>
 *   <li><b>No duplication</b> → reuses canonical {@code ServiceResponse}</li>
 * </ul>
 *
 * <h2>Composition Model</h2>
 *
 * <pre>
 * ServiceResponseCustomerDto:
 *   allOf:
 *     - $ref: "#/components/schemas/ServiceResponse"
 *     - type: object
 *       properties:
 *         data:
 *           $ref: "#/components/schemas/CustomerDto"
 * </pre>
 *
 * <h2>Vendor Extensions</h2>
 *
 * <ul>
 *   <li>{@code x-api-wrapper} → marks schema as wrapper</li>
 *   <li>{@code x-api-wrapper-datatype} → underlying data type</li>
 *   <li>{@code x-class-extra-annotation} → optional generator hint</li>
 * </ul>
 *
 * <h2>Important</h2>
 *
 * <ul>
 *   <li>This class is responsible for <b>creation only</b></li>
 *   <li>It does NOT inspect or modify existing schemas</li>
 *   <li>External schema normalization is handled separately</li>
 * </ul>
 */
public final class ServiceResponseSchemaFactory {

  private static final String SCHEMA_PREFIX = "#/components/schemas/";

  private ServiceResponseSchemaFactory() {}

  /** Creates a wrapper schema without additional class annotations. */
  public static Schema<?> createComposedWrapper(String dataRefName) {
    return createComposedWrapper(dataRefName, null);
  }

  /**
   * Creates a composed OpenAPI schema representing {@code ServiceResponse<T>}.
   *
   * <p>The resulting schema:
   *
   * <ul>
   *   <li>Reuses the canonical {@code ServiceResponse} base schema</li>
   *   <li>Overrides only the {@code data} field with {@code dataRefName}</li>
   *   <li>Attaches required vendor extensions</li>
   * </ul>
   *
   * @param dataRefName name of the concrete data schema (must exist in components)
   * @param classExtraAnnotation optional annotation hint for generated clients
   * @return composed OpenAPI schema
   */
  public static Schema<?> createComposedWrapper(String dataRefName, String classExtraAnnotation) {

    String dataRef = buildRef(dataRefName);

    var schema = new ComposedSchema();

    schema.setAllOf(
            List.of(
                    new Schema<>().$ref(buildRef(SchemaNames.SERVICE_RESPONSE)),
                    new ObjectSchema()
                            .addProperty(PropertyNames.DATA, new Schema<>().$ref(dataRef))
            )
    );

    // extensions are part of CREATION → authoritative
    schema.addExtension(VendorExtensions.API_WRAPPER, Boolean.TRUE);
    schema.addExtension(VendorExtensions.API_WRAPPER_DATATYPE, dataRefName);

    if (hasText(classExtraAnnotation)) {
      schema.addExtension(VendorExtensions.CLASS_EXTRA_ANNOTATION, classExtraAnnotation);
    }

    return schema;
  }

  /**
   * Enforces wrapper-related vendor extensions on an externally created schema.
   *
   * <p><b>Use this ONLY when:</b>
   *
   * <ul>
   *   <li>Schema is generated by external tools (e.g. springdoc)</li>
   *   <li>Wrapper already exists but lacks contract metadata</li>
   * </ul>
   *
   * <p>This method does NOT modify structure (e.g. {@code allOf}), only extensions.
   *
   * <p>This method is idempotent and safe to call multiple times.
   *
   * @param schema target schema (must not be null)
   * @param dataRefName underlying data type name
   * @param classExtraAnnotation optional annotation hint
   */
  public static void enforceWrapperExtensions(
          Schema<?> schema,
          String dataRefName,
          String classExtraAnnotation
  ) {

    if (schema == null) {
      return;
    }

    schema.addExtension(VendorExtensions.API_WRAPPER, Boolean.TRUE);
    schema.addExtension(VendorExtensions.API_WRAPPER_DATATYPE, dataRefName);

    if (hasText(classExtraAnnotation)) {
      schema.addExtension(VendorExtensions.CLASS_EXTRA_ANNOTATION, classExtraAnnotation);
    }
  }

  /** Builds a safe OpenAPI $ref string. */
  private static String buildRef(String schemaName) {
    return SCHEMA_PREFIX + schemaName;
  }

  /** Lightweight null/blank check without Spring dependency. */
  private static boolean hasText(String value) {
    return value != null && !value.isBlank();
  }
}