package io.github.bsayli.openapi.generics.server.core.schema.base;

import io.github.bsayli.openapi.generics.server.core.schema.contract.SchemaNames;
import io.github.bsayli.openapi.generics.server.core.schema.contract.VendorExtensions;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.media.Schema;
import java.util.Map;

/**
 * Applies generation control semantics to OpenAPI schemas.
 *
 * <p>Marks schemas that should NOT be generated by attaching {@code x-ignore-model}.
 *
 * <h2>Scope</h2>
 *
 * <ul>
 *   <li>Canonical base schemas (ServiceResponse, Meta, etc.)</li>
 *   <li>Derived container schemas (e.g. PageCustomerDto)</li>
 * </ul>
 *
 * <h2>Key Behavior</h2>
 *
 * <p>For container wrappers:
 *
 * <pre>
 * ServiceResponsePageCustomerDto:
 *   x-data-container: Page
 *   x-data-item: CustomerDto
 * </pre>
 *
 * <p>This class resolves:
 *
 * <pre>
 * Page + CustomerDto → PageCustomerDto
 * </pre>
 *
 * <p>And marks THAT schema with {@code x-ignore-model}.
 */
public class SchemaGenerationControlMarker {

    public void mark(OpenAPI openApi) {
        if (openApi == null
                || openApi.getComponents() == null
                || openApi.getComponents().getSchemas() == null) {
            return;
        }

        Map<String, Schema> schemas = openApi.getComponents().getSchemas();

        markCanonicalBaseSchemas(schemas);
        markDerivedContainerSchemas(schemas);
    }

    // -------------------------------------------------------------------------
    // Canonical base schemas
    // -------------------------------------------------------------------------

    private void markCanonicalBaseSchemas(Map<String, Schema> schemas) {
        markIgnore(schemas, SchemaNames.SERVICE_RESPONSE);
        markIgnore(schemas, SchemaNames.SERVICE_RESPONSE_VOID);
        markIgnore(schemas, SchemaNames.META);
        markIgnore(schemas, SchemaNames.SORT);
    }

    // -------------------------------------------------------------------------
    // Derived container schemas (Page<T>)
    // -------------------------------------------------------------------------

    private void markDerivedContainerSchemas(Map<String, Schema> schemas) {

        for (Schema schema : schemas.values()) {

            Map<String, Object> ext = schema.getExtensions();
            if (ext == null) {
                continue;
            }

            Object container = ext.get(VendorExtensions.DATA_CONTAINER);
            Object item = ext.get(VendorExtensions.DATA_ITEM);

            if (container == null || item == null) {
                continue;
            }

            String containerName = String.valueOf(container);
            String itemName = String.valueOf(item);

            String derivedSchemaName = containerName + itemName;

            Schema derivedSchema = schemas.get(derivedSchemaName);

            if (derivedSchema != null) {
                derivedSchema.addExtension(VendorExtensions.IGNORE_MODEL, true);
            }
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private void markIgnore(Map<String, Schema> schemas, String schemaName) {
        Schema schema = schemas.get(schemaName);
        if (schema != null) {
            schema.addExtension(VendorExtensions.IGNORE_MODEL, true);
        }
    }
}