<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.blueprint-platform</groupId>
        <artifactId>openapi-generics</artifactId>
        <version>1.3.0-SNAPSHOT</version>
    </parent>

    <artifactId>openapi-generics-contract</artifactId>
    <packaging>jar</packaging>

    <name>openapi-generics-contract</name>
    <description>
        Canonical contract module of the OpenAPI Generics platform defining deterministic response semantics
        (ServiceResponse&lt;T&gt;, pagination, and error extensions) shared across server and client boundaries.
    </description>
    <url>https://github.com/blueprint-platform/openapi-generics</url>

    <scm>
        <url>https://github.com/blueprint-platform/openapi-generics</url>
        <connection>scm:git:https://github.com/blueprint-platform/openapi-generics.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:blueprint-platform/openapi-generics.git</developerConnection>
    </scm>

    <contributors>
        <contributor>
            <name>Baris Sayli</name>
            <url>https://github.com/bsayli</url>
            <roles>
                <role>creator</role>
                <role>maintainer</role>
            </roles>
        </contributor>
    </contributors>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit-jupiter-engine.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <properties>
        <junit-jupiter-engine.version>5.14.3</junit-jupiter-engine.version>
    </properties>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>


        </plugins>
    </build>

</project>