title: OpenAPI Generics
description: Deterministic, generics-aware API platform (contract + server + codegen)

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

baseurl: "/openapi-generics"

toc:
  min_level: 2
  max_level: 2

aux_links:
  "GitHub":
    - "https://github.com/blueprint-platform/openapi-generics"

search_enabled: true

mermaid:
  version: "11.6.0"

ga_tracking: G-4NH21XZLBN