title: OpenAPI Generics
description: Deterministic, generics-aware API platform (contract + server + codegen)

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

baseurl: "/openapi-generics"

just_the_docs:
  custom_css:
    - assets/css/custom.css

aux_links:
  "View on GitHub":
    - "https://github.com/blueprint-platform/openapi-generics"

search_enabled: true